// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByHuM_odwBAN3WRbtQouhsBuwhBwaVQBY',
    appId: '1:233070326370:web:6d1a127f686edb21f8d73b',
    messagingSenderId: '233070326370',
    projectId: 'uploadfile-e46d8',
    authDomain: 'uploadfile-e46d8.firebaseapp.com',
    storageBucket: 'uploadfile-e46d8.firebasestorage.app',
    measurementId: 'G-6B176NK1GX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCSLtIl3F2AmZhxyITvr4nNoEMxmOpOZg',
    appId: '1:233070326370:android:bde8901134fb16f9f8d73b',
    messagingSenderId: '233070326370',
    projectId: 'uploadfile-e46d8',
    storageBucket: 'uploadfile-e46d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbjksCJYsV9MuTIQgoRONZhmMMmBmqC_c',
    appId: '1:233070326370:ios:54be71a5cf5a0824f8d73b',
    messagingSenderId: '233070326370',
    projectId: 'uploadfile-e46d8',
    storageBucket: 'uploadfile-e46d8.firebasestorage.app',
    iosBundleId: 'com.example.uploadfile',
  );
}
